### ISSUE TITLE
$InvitedTime Error

### ISSUE THREAD

**Issue by mikki-mc** [Tethered/FactionsPro#20]
On version 1.3.0
Many command make crash :( but i dont remember what the command cause i was fix it self...

But on your ToDo for InvitedTimeout will be configuration is buggy :(
Please fix it.... this plugin is essentials for my server xD thank you

**Comment by MCPEPIG** [comment]
1.3.0 isn't done yet.

**Comment by rj0495** [comment]
I think he is gone.

**Comment by rj0495** [comment]
I'll see if I can takeover. This is an interesting project

**Comment by Tethered** [comment]
No, there will be no "taking over" of the project. I'll be updating soon but I haven't had a ton of time on my hands.

**Comment by rj0495** [comment]
Ok, I was only saying I'll take it over if your no longer working on it. It
seems interesting

**Comment by Tethered** [comment]
Well, I'm back at it and 1.3 is about to be released!
