### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by devin5411** [Tethered/FactionsPro#21]
When I do /f promote it crashes my server, please fix this.

**Comment by Tethered** [comment]
Can you upload the crash log to pastebin and send me the link?

**Comment by devin5411** [comment]
Yea ill see

**Comment by devin5411** [comment]
Join my server real quick my device is updating so Can I use u as a test monkey? IP: factionspe.pocketserver.net PORT: 11221

**Comment by devin5411** [comment]
http://www.paste.org/78795

**Comment by Tethered** [comment]
Fixed. Thanks for pointing this out!
