### ISSUE TITLE
Latest update is bad

### ISSUE THREAD

**Issue by flaxues** [Tethered/FactionsPro#24]
The latest update of FactionsPro gives many errors and crashes

Some errors: http://pastebin.com/ctvk1ZMA , http://pastebin.com/MG9bPsi0

I tryed to get the BannedNames file from github and placed it in the FactionsPro directory but still gives the error that the file is not found...

**Comment by Creeperface01** [comment]
Fatal error: Call to a member function sendMessage() on string in phar:///hlserver/27750/plugins/FactionsPro_v1.3.0.phar/src/FactionsPro/FactionCommands.php on line 302
14:33:40 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
14:33:40 [EMERGENCY] Please upload the "/hlserver/27750/CrashDump_Thu_Jun_11-14.33.40-UTC_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by Tethered** [comment]
This issue has just been fixed in 1.3.1! You can get it in the releases of FactionsPro here on github or in the PocketMine repo when it gets accepted.
