### ISSUE TITLE
Claim Bug

### ISSUE THREAD

**Issue by BobbyTowers** [Tethered/FactionsPro#26]
Every time I try and claim land/plot it crashes.

PocketMine-MP Crash Dump Fri Jun 12 02:37:15 ACT 2015

Error: Call to a member function sendMessage() on string
File: /FactionsPro_v1.3.1.phar/src/FactionsPro/FactionCommands
Line: 318
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: FactionsPro v1.3.1

Code:
[309] 				if(count($args == 1)) {
[310] 					
[311] 					/////////////////////////////// CLAIM ///////////////////////////////
[312] 					
[313] 					if(strtolower($args[0]) == 'claim') {
[314] 						if(!$this->plugin->isInFaction($player)) {
[315] 							$player->sendMessage($this->plugin->formatMessage("You must be in a faction."));
[316] 						}
[317] 						if(!$this->plugin->isLeader($player)) {
[318] 							$player->sendMessage($this->plugin->formatMessage("You must be leader to use this."));
[319] 						}
[320] 						$x = floor($sender->getX());
[321] 						$y = floor($sender->getY());
[322] 						$z = floor($sender->getZ());
[323] 						$faction = $this->plugin->getPlayerFaction($sender->getPlayer()->getName());
[324] 						$this->plugin->drawPlot($player, $faction, $x, $y, $z, $sender->getPlayer()->getLevel(), $this->plugin->prefs->get("PlotSize"));
[325] 						$sender->sendMessage($this->plugin->formatMessage("Plot claimed.", true));
[326] 					}
[327] 					
[328] 					/////////////////////////////// UNCLAIM ///////////////////////////////

Backtrace:
#0 /src/pocketmine/Server__32bit(0): pocketmine\Server->crashDump()
#1 /FactionsPro_v1.3.1.phar/src/FactionsPro/FactionMain(70): FactionsPro\FactionCommands->onCommand()
#2 /src/pocketmine/command/PluginCommand(57): FactionsPro\FactionMain->onCommand()
#3 /src/pocketmine/command/SimpleCommandMap(191): pocketmine\command\PluginCommand->execute()
#4 /src/pocketmine/Server__32bit(2020): pocketmine\command\SimpleCommandMap->dispatch()
#5 /src/pocketmine/Player__32bit(2472): pocketmine\Server->dispatchCommand()
#6 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket()
#7 /src/raklib/server/ServerHandler__32bit(90): pocketmine\network\RakLibInterface->handleEncapsulated()
#8 /src/pocketmine/network/RakLibInterface(79): raklib\server\ServerHandler->handlePacket()
#9 /src/pocketmine/network/Network(146): pocketmine\network\RakLibInterface->process()
#10 /src/pocketmine/Server__32bit(2483): pocketmine\network\Network->processInterfaces()
#11 /src/pocketmine/Server__32bit(2300): pocketmine\Server->tick()
#12 /src/pocketmine/Server__32bit(2178): pocketmine\Server->tickProcessor()
#13 /src/pocketmine/Server__32bit(1783): pocketmine\Server->start()
#14 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct()
#15 (1): ()
#16 (0): {main}()

PocketMine-MP version: 1.5dev #1240 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT SERVERMACHINE 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
AdvertisingKick 1.0.0 by  for API(s) 1.0.0
ChatScribe 1.1.0 by aliuly for API(s) 1.10.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
CustomAlerts 1.5 by EvolSoft for API(s) 1.12.0
EssentialsPE 1.1.0 by LegendsOfMCPE Team for API(s) 1.12.0
FactionsPro 1.3.1 by Tethered_ for API(s) 1.12.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
PocketMoney 4.0.1 by MinecrafterJPN, MinecrafterJPN for API(s) 1.10.0
PurePerms 1.1.2 by 64FF00 for API(s) 1.12.0
SignShop 1.0.0 by xionbig, xionbig for API(s) 1.11.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
WorldProtect 2.0.1 by aliuly for API(s) 1.10.0
PureChat 1.2.6 by 64FF00 for API(s) 1.11.0
KillRate 1.2.1 by aliuly for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNOw1T47a2f0U3uzOFN3ES5wtIh53hAdvuvXzkAvu29zYdRrblxBfbci2ZkO3sf3/nHMmObaDs
tvTNo2XWPpLO95ck81tHR4nozNzxaDw4GE9Hk25H5LnMO7PfOnqTwVDn9Pb06uryqtPtJEIpvkTY
MY9jpiXjLBGJJ3IWFqmvI5kyJdLg3Mzb2WUI0HmULmF1GMW4tP+e00w1z+Xtvdsb9dxetuJ5X+V+
fax8PpZJwtNAAYY4SgHDyN3/0u1kcbGMUsBXWwJTfBkI5H00OICxhTb/ReGOL4tU77zl+VKxw0Pm
7u6y32D+yB3U5i00gdwGqP/7P+z47OjDOXthFuEdPiY1aoCAT1CXlrFci9ww+/Pgl11k+Ds/5lHy
Xcn1uLGOVv7trV5FynlnNOO8i9SH1Cpn520W843IK6EnreULbWc47+oGbGEMZZ5wXQ4uOv+SBUsK
pZknWJSCM4SGXG/R2d39nghNW4S+EHTva7g/EzxALbRY33911mMihO5cKMFwXU2Ag6cEGA5a0LcP
7JCFsZTAL3KB3CyF/mnHohm67QWbJxf8q1owbC/4/OSCf1cLRu0F1hiwrKULWDYnjVXeUUNoRnZ2
6eWCJ6Ii0Ha5FtYg5+t5LHVpsC4rOYCnB/jdwO9n+H2O2Jm4F/HObrfNbpaLUNEMsBtSuI4+i8pA
w7YrV/i/wRsQK6MAEwHYvst0XoiSQNOFjf33HkXycP+bksbHi69LG5DpdM59yGk/d94MGCXJTPp3
QieQDPvXIr8X+e3taOhFemewO2PbwcXCjDrv/Jyr1UmRZDu7wOobl31rDj7nUbqzh+hrg4tFK0M7
76pnQ2j4iF/fDPfnZIhy8mTvGcxI9xHW0bNYr6Mki4WdfM6zHffAbanETl0sGhw478SD8AstDIXx
C3oeDoaD5/C2eYDAiFTGtb8yuCePcJsgqHCP94bPmLFE1NDG9BG+VOi1zO/6V/zuLPI+pFrkEIhi
xx23mZ7bvLkCbLE44ZrPOY4azHsGc87v4sjrK2LCKuJHWlDxfNBGbFlYLFo8lKROU59nqoi5FlaM
/a8WY+8AiBmmFgvDVakiy1ZJpS7MwbP4L8y/oJ7pV0uR5dKH5GHD6aWwHI73R8+httQrlBWRErn7
EvLR4Lmw15F/Z7EMX8Li7u3/Dpa5YQ5qj0E3egEdYBs9g05pnlubuI/jbE6P5/C4M56On0Fxe+tD
noAU7ZeIJmwHA92+TRllwt8SyB5fAPZLt7MUqch5jJ0hoFCQWiBbu71JIO5hiVdEcQBN8HA8gMYy
l1r6EuYO97odnkU00x32BjBzGWl4HXzlDywwjoprenuEoUg5NtydT1EayLViFzfs+vTqf06vzo+O
f/xwccqmPZcRQ2xvOnDZTjlxj/13oUAPSrHTIKLKjgqJfMHQ0aGjZdFkfwokslUGBCa9aQ/fPkMZ
hNchvA7M4K1UyMCHi4sbANDLGlrpqqlWqKajABSlI6C4/Ad4AIIs5+2RbkOlA6LCC72SOSD6+Rer
w5/tGLyLlHuxAKawynY7gcgE9vc0V8lQn9QBaERAfMLzu4uRUotFi/wjAO4TJEeR55fXN58ur85O
ALQWnoo0sJ8WcQySHq+4vvbzyBM1yWrAplBuS6gOj6Mi3nTqwrl/QjqDDqoIMKCIgcUCa99XyiIT
j+szuVyKvC5NHdyUZ9iW54wnnmyKM/zj4hC2xaLOwDfJA325TI4gk2tVl6cObsozaUpzei/ja+Dt
1QSqkwa5moxYia5vjq5uPs7r8nRWWmezfn+9XvcE8IToe/oOI+1UQXuqIx6r+WlNxgb4BR88E0tk
9DI8P56fshvBk1eTt87GYnEmcX/0gu1IVgXCQopcFV4PGqK+4dAw2G+IBhqo79u3Cmju5uvyQ4/a
lP9G6JXIRXD7amI/14J+ndu+50rf5DxVYSMMG+B2rhw2RVIruVxFfvZqEpUIUZwtG823l124ZdYS
ab+BBTRwzpeRfyOg85K5NtXWKqE90jbt8P8kvSY6+5Y8NBfQh4VFfJ3xdVoTpgmviTLsjZsRevJT
Qwbjwm5v/CdS68lP0LfXGfgmiaib+qHgeVCXpwatG2YIOacVc9iZwW4yhCb17/OLVzNQEy0I2ODo
W9NOE1u/hoz207bHlKnYPFKCgdaVALZ6QQndv0orNZZKlZT8vYpKDDLUSJGLuciTerXdwtplqBWr
0/H794PBq2WsW4MPBC4ZqD1+c6qilaap7W+xgMjX0TK9XsmsJnEF+v2GtvMAI16EJ9rlU0N294/L
XnKApwgVLy+aGiS2jPR4rHFLAHusnsyX/QoLCYznEkcgRkPkCtgUeq/t89uNmek0uq9fq7bMlKco
lrFvNHnFab+GBTTwSeZxAKVdC1/XdNAAN9Pfo8j/i+rSGlnIDAvtdP6E1GUyB3/GHUsraAnUbven
L8fsS35bywiPRGq0bc/EMvK1ffrTkUxIQAv/iOL4iuv6Nq4CtbXwV1izVTjOuVLRvTj1ZSoTBNin
o/kHePlBxsG1DjqPXeAOeM6B56+v5rhd5zlIDCFfckYHJD3wpAx3xAJ39m/m1Rs7lmkYLRlexC3y
RfrmfR6xvxcpc4dsMJyNJrOJy46Ob9hw4E5wgsHnoFoPb/BKClBgEWGwK9gOZ9DSHboH7miEwEQk
Mt84cZRE+nDiDs8RuOQIDsThgKbwB8fcEahDd0AghZ2MY0MADHY4GiJ4vQJ5AZfShzIMEWIM4/xa
iHzTguWg6RKUSB1YloljhPE0lUXqC0vb4f4qEvcigV2JOpQpTYljuXbCOFquKoqGNZ5GCWxdmsBE
ehUklDmgrgS10BU0Hb7Mq/fsPrOkgigMI7+I9ebQJRXRCZWWuaOE1lG6VIcIjvFSxFiAssQWpoQI
alPwsvbw5PT90cezG4SiNnoZeCMsCw7/i35AwEJLR/F7YbnAA6HqhK23SWL0GIYuyHxylgJ4wqMm
9BkGMrJtenXO5+BD7GYllGAl04zneIUmGMSDggeumY+Kt3eEflwEIsDLwke+iriuZQIrQ0TQxql4
KLpM4pZPIUrm5YLfsY0scouLRSED3UdhRBRA7Tk4EwQXIL4Q6wpdPxAhB8Urtpbpd5rxLBM8Z6ia
BIT1wQk2eHGNV0ZG7vVKpKzIljkPAEFvkaLvG2SzRcre3KxyAW4KIOAi5umy4EvB8CqaVGbjREXw
HkvAH30mpeLS45XwrRTNhcBAmQVF2ltHd1EmgsjUdXzrn0FU3Mrw9sP15e10dOAMb3EdqLFCNGML
SGTLRQcJfVrRdhlvOfFijOEFvrmaBzPhHo4O480waZM4BT7gSWgyaSDotNEcriMkAcTG77ckQ4gS
AXC1KnQgMUjMLRsyYw5wmR9LBaQA85Wg4+CoZPII449hvAOI2dNIdh9x9k8MeJhCge/YkS21N9Dm
rBlHp1USmLNEjeW4xYTXuwqkyMAvSFhIyjAT6kGAatsOOMClBzzO6B4Q0Z9SiinxgAIYRjUD7wUH
QV69DbNuBdNtQqpGa3x+gjwPtgUP40HAcqGMIyKbeNAO7HAF1Q2TEgP38wQqBDQlfi04fXGxhOqS
snseF4LtWJKQsHcBuaEHiVBgSnbAuHjyNoNRpHxR0IcaEF1HapP6N1zdMbx6gHjq4fhHtAm6aykk
zlrlUL0K8BCYrbqMUhCzqYpudqE0g9YUFllSC9QohCVFCoFkvgVA65AHgTwQa7l8gFSqBagAxCHP
TyvWUKuGnQ8hBix9YwKB2WWR/g4/OclpVSCwTpBTttayHZAAr/GHqBGSwbFSzggTBq+pURS6P8TS
A8ViTWcGzKh0YYpKxJJ7Gw0MsWvDyoCIRwrNawIfZFpHxBgpm2H9sCXQghTpJYzAXSBrQa5OCVUI
KaOkaMwPwhTktEsJckiMFNQZ0FkSk6amzhgU1QXlDkrTGnIPD/6fC4DNTsn+CN0RaUMvGUmqBej5
CnH6lA0t0sq7XfAECOwALUozHOyUjF9TDpUp5AuIB+ARY/E5EQzr0FPElF4xssy0BVU7xAG+vo0b
E/xI4RIDFssLTe89noyxantG0HUmfKxCilSCvBpjmLWVAJB+Raa2Yo4GVk61+yRDVuqRkXrJcw90
7fgyjk3PhP78pFbJdMiKXcPsGoiUhKcF1bs6F9ALFOA0u90yAlteY93GZLEwLCMx2bpjj12aYkNv
CoqBLOKgYiSCeF2nbMs6+gjLiHMQcDoYGBnZm/fkdY8yEfmKWV0JFeYyKRMarrXjTj0H1GwKQljT
tV3hCf+prcPm1V8V6Z0y+j6jYMP0Q0DkDFt3lIaVH8JgKORQ/ZWZ5GABxkZiiwtRlWa2cXIwtXye
SLOsbT5MudimmGV1DIaKnfYKMlPad3xomIWR2vpCSQgHqlr5u6gWqb35rvomcI3Y1B0Pv22guk/3
9lBuwJ9s+qIANF2hHTVZyxNVBRJBVWmsx5YjGPj5RiPuLnPcmjNjpSGyji5ZgbQymZqssq1s1GJj
WQlMqrMGNGsBaHnqsR9h5wDqPYRGFBz3eP6xC2uBAw/yzzoK9MpkSIrvCr1D6Gdsz5bhbYFWpJja
1B47CiCeVjwO+9Bhm54hEOBnlhCQNP4n03pAVrWwhqvWlZw+YPBh08HjrglsJGyvnnsM3Eao8gO5
j/N0XtblbcOMLQcuWsOOZ4Hdcpo59rXeAcHGR3jFcmZL/DvmYmk3xlTYw9Fw2b8pymMrUfZ1C2uK
GXO3XZlifegidQEO01/6RrX0PVKNaLllajTtomzZmPkezGxXaKp1LxSXDO6DEjV5mF3imCUzlsDQ
0jbzIBCdFyC7eCetTFLiDfyQOXE7pGvkQZn6MTcUo2S6NxeXN6czRlkX/vcL2NmksLMhRHTGhaYj
9izlir3KxEcNa/nQxC9FKSt5EZUk4AS9RqPnDAe2hGAqM5UJ3Qh3kAi35chGfRNc5jDTeV5juKKA
HleiRmzHhUB5gkqXDWHAfWpAaL+3S0GrRJ0LcocbxIz7Gnu4wAQkJkMPS7+xJO0gt1tLTAS06TCf
fYIg8ZpvlMFt8dT8qJG/yY2OEvywuFYAlO2PSiaQfcSGDTrkZnycsfHzS3kO0MDwbnA0qw5zD4ZP
ribvSoXZxHnCYPNEiJmIziswY6EZKqzmFKOW+kzmu+b3UHRxHxjhXlXgZifb2H25rUVVQ0OJIuRK
k1ZJLzaNhUVM06QCV3UwRCPflBLa8OS4GQbHALSlqv4jcd9hYkPxBH0loVyJBaaSv6wlxhaoz9IW
5/yB8bZa7IdVIti6Q9MU5KNXsLUvVG2ZNQO3zFGMmqXW7XA+NCuYkvC4yCmyAFyxtif1Y8ENETrB
ajO+3UWVvPceM2/T35pHtCOG3W8hrHnteop6gjsKbDVj+38IWyYz8zke6sY8Y2VqIV6kFJIOaA+Z
NodiDrmRQk2iKhP8NguPOyzUtdkBT51mzPR2pUVBQ2mRQa9jGj7jj5Q7TJ9hcQGWPVxlCSLSCb6u
ORKqgATjiReB45sp9sDLbIhnJhfh3h2/h2UGakqsdRLjvLaRr51lwCIHT1eqdEeQqpw0oNkqi9JQ
blevJBqfaPZqh23QCBGDqUw3Cbb5FCEKFKwqTnHfYofZdpg4BmfjjC+XUH3sVrw65MAeET8avntG
HMMQ4lNPMYQaM85MRn60HNzCDM+MDfLUseV5O8eAZVY/ojnGQzs6RRKxzLBideEdpMAjMl22Y/i1
N3TLAhQONSrFWo+TbHnFL+CWEJQ1JMye8df6iAKaTqVNkSuTnsWGVjLDJX7VVgx+rfOEWuIIao4x
zekDx6JrXrBrAQKWi1nJDg2ByystwcF/xkcHKg3sqQDwC2I0qbDsRernnSRFuWkwO7fydJi2ZE8d
n9IOl0qZorYB5U6gm4iAUVvna6wTVWKAnhgeJmMAU13aUpux92dHN7Ph93vdycGD2x09jLrD793v
AyjHJnft6FwI+tuaw/0BW4KTK/M2nuzS8bJ40CJFhdDl8jEUo9q3iZ4PLcmqMyMDdDt44JgGPN8C
zJ8g2beArnmqxVBBltVYGOHVJ31n6ZovpUKdVaMriD1zmQsDEfZI1dB/VON6CNq5Taar0ev5GeHE
O28ZeH6FJPPzLWNXIrQbMhh/+wE0KcJw3wv86cQbeIKH++GYB2IaDqbh/nhfTIPxKAiD/eGUvcWb
VNOPV+ggGFALQU3WZKN+jek7TvvEJng76ToQCMzBC5vhYDIYwSORH/nT/X1v6nn+aBCMpjwccX80
DoNg7O15E29vfy8UE/gh8lreiRQyvNUefjIaZeVHr2N8NV+wmo8G4fkBrwlKm8gEhwaDkesOD2B8
fnJpr83H5uPa+QoNSrepqEVzJ/vT+VlFbR0EDxW+Om54zulPc6qpAFnnka5BPgl+BxnDGIlUBd3x
FgVpK6pm44sWI/M5rmP4UxTqarvEs3+xVgI2nK5FXPs1TGYPNcob4gH91VlyG0gNqaIilRifszj+
jWXnck5lD6bsoXqQ/nv8yu+B9jyED0X48uV/Acss4So=
===END CRASH DUMP===

**Comment by Tethered** [comment]
Fixed! Thanks for noticing this, this bug was in a few commands!
