### ISSUE TITLE
So MANY CRASHES!!

### ISSUE THREAD

**Issue by TheEpicCooldeal** [Tethered/FactionsPro#27]
THIS PLUGIN IS TERRIBLE! ANY COMMAND THAT IS WRITTEN CRASHES THE SERVER

ALL OF THE CRASH DUMPS ARE IN THE .ZIP FILE!

ALSO PLEASE READ THE "PLEASE READ" FILE!!

Link to download: https://www.mediafire.com/?870ypbb7a11bqx5

**Comment by Tethered** [comment]
When does /f kick crash the server? When player A is in a faction and B is not in a faction and A tries to kick B or misspells B?

**Comment by TheEpicCooldeal** [comment]
no it just when someone does /f kick it crashes the server.

**Comment by Tethered** [comment]
Check the latest release
