### ISSUE TITLE
Crashdump

### ISSUE THREAD

**Issue by flaxues** [Tethered/FactionsPro#33]
PocketMine-MP Crash Dump Sun Jun 14 12:28:15 CEST 2015

Error: Call to a member function isOnline() on null
File: /FactionsPro_v1.3.2.phar/src/FactionsPro/FactionCommands
Line: 138
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: FactionsPro v1.3.2

Code:
[129] 						if(!$this->plugin->isInFaction($sender->getName())) {
[130] 							$sender->sendMessage($this->plugin->formatMessage("You must be in a faction to use this!"));
[131] 						}
[132] 						if(!$this->plugin->isLeader($player)) {
[133] 							$sender->sendMessage($this->plugin->formatMessage("You must be leader to use this"));
[134] 						}
[135] 						if($this->plugin->getPlayerFaction($player) != $this->plugin->getPlayerFaction($args[1])) {
[136] 							$sender->sendMessage($this->plugin->formatMessage("Add player to faction first!"));
[137] 						}		
[138] 						if(!$this->plugin->getServer()->getPlayerExact($args[1])->isOnline()) {
[139] 							$sender->sendMessage($this->plugin->formatMessage("Player not online!"));
[140] 						}
[141] 							$factionName = $this->plugin->getPlayerFaction($player);
[142] 							$factionName = $this->plugin->getPlayerFaction($player);
[143] 	
[144] 							$stmt = $this->plugin->db->prepare("INSERT OR REPLACE INTO master (player, faction, rank) VALUES (:player, :faction, :rank);");
[145] 							$stmt->bindValue(":player", $player);
[146] 							$stmt->bindValue(":faction", $factionName);
[147] 							$stmt->bindValue(":rank", "Member");
[148] 							$result = $stmt->execute();

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1244 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux MineCraft 3.13.0-54-generic #91-Ubuntu SMP Tue May 26 19:15:38 UTC 2015 i686
PHP Version: 5.6.8
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CustomAlerts 1.3 by EvolSoft for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
BuyCraft 1.2.1 by Falkirks for API(s) 1.0.0
EssentialsPE 1.1.0 Beta 7 by LegendsOfMCPE Team for API(s) 1.12.0
AdvertisingKick 1.0.0 by  for API(s) 1.0.0
FloatingTexter 1.0 by Heromine/Jon for API(s) 1.12.0
RARFix 1.007 by PEMapModder for API(s) 1.11.0
PurePerms 1.1.2 by 64FF00 for API(s) 1.12.0
AntiTower 1 by xpyctum for API(s) 1.0.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
iFriend 1.0.4 by LilCrispy2o9/Angelo Vidrio for API(s) 1.11.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
FineJoinEffects 0.4 by Asidert for API(s) 1.0.0
PopupAlerts 1.2 by EvolSoft for API(s) 1.12.0
WorldGM 7 by Exxarion for API(s) 1.11.0, 1.12.0
PureChat 1.2.6 by 64FF00 for API(s) 1.11.0
KillRate 1.2.1 by aliuly for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNOwtT47bWf0XN7syFO3HIiwDZYWe4LLT0wpKPZLv3m6azI9ty4mJbriQDaaf//TvnSH4F2mV3
uTMffWAfSef9kiz+6Jg4FZ3pYDwaDw8OJkf73Y5QSqrO9I+O2eQw1Dn7dHZzc33T6XZSoTVfIeyU
JwkzknGWitQXikVFFphYZizW11kSZ2Jnl8FbViQJLIziBFftnXOapGdKfrob9Ea9YS9fc7WnVdAc
K59PZZryLNSAAVECm6PDP7udPClWcQb4GktgSiBDgWwPhkcwtjT1P3G0891rs46199au9d7G+iJz
y3dea5GFQnlvV8K85ymwvrvL/gCMg1F/C9PSVJPx95VVyM4W8kiqlJtycNn5X1mwtNCG+YLFGSgt
spRRg4UWDFd/t+zs7r4hooMton8SdPgcoS4FB+Z2XucJ3whViTF6cTESItQUoOZ//CT/+4/536IH
6p8R35VhnBjsu2P22blcrfTPg18qmScvIvNJGDLLBcpa2i2KlTYNix1sS4z/o5HDz1sNRJkLdQdm
223IdfYAtGqp0LhlYJUSHr2IhJYcy6SBgEUCtVzj/lOWHA8e03WKwehhz7CVs6slMnxZdNbX6XH8
hIJMah6jDH14ViLnCjVy8X5+drNg1zfs5mx2eXJ6xi7eL65ZyrUBRe1Yat3SGbpM8ex2l/10cvnh
bM52puX4tJowpRlvQK+Wxf2n+fLe+nEW/sSTArlweJadLmsLOHnWakecljfU6XAcPAsHso0Ilp0r
yvKVAIePlyuhi4RUaxGJBxEUBrz1TQdStlE8gOT8c+dVn+3sTlkug1thUvC25dI6v/c2UFyv3xVp
vrPb+aXbWYlMKJ5gRodhDfwD0UFvPxR3wINfxEkIBWE4HkNBUNLIQMLc4UG3w/OYZg6GvT7MXMUG
XvvP/IEFit8msY9regeEocg41sjOZZwVD+wKmD5VPDJs1BuMen1vf+wRr3HAXh0NvA9+kZmCza9m
bFEIdsU3bDhhg6PpYH86OmQfFqds2B/ss3hyOAHk+ToH1Pu9Se8Q3n6HuIXXIbz27eAnqUvSAKCX
hF6qQqhRRQso465cCirejuc2vFurcgiKKsxaKo1muXz3H9Q5qe5n0F2fyIMO3e+h+z1yv8fwG+aL
jPuJAI6NKkS3E4pcYLme/gxjWkbmXROQciraQGq5bLG1XF7hEBR5yVH62fV88fH65vIdgO6Fr2MD
kmAnASKfQuFRl3y1ashYw7otV7HMN6UUYKjwOro6nZ09EvcrxamIL5eXklsl/50cnbUxuZ7u7YFf
rgu/F8h0r8nXXi0NigvlVqYniVBGNyVugttCj9oin93JZA6st8SlyPhaeRukl8stRpzg88XJzeLD
7JHYIPX9/X1PAE+IvmduUcYY2jcjAiObftsANuWDkOOdv/Xco2/0zJrws9zySXO++49HpmwIAXL+
BM834p6rsCFnA9gMzt7gq8PzW4SvufmSmJzHaZ6IE2C3IVgD2HbQg96gbcEZ1QJMq2wheAqDei1X
6zjIX8xpa2ag3DQZ+4zDbhm25nSvgQVNezGbJ7IVohWoKT3YrTduSx//KPW64D+8ezFhK4xgz5qJ
L5M0/pVwrMO9CgVmI5n63FzK1apVY1rgtrGHj1IwT335YqISNshCDQa+xHH/VWyokjdkqUDbcmw5
7TlPbmN1q1+qjPjFJkC6y2WDg2eIcKah1TcxTzSUtFqMFvhRVWT/Eoazg6eKo7ZVyEbiS5mpyc1L
lcmWhKCIkxCENLGOs9W/4+C2oYvtkbY6+lse+kL2fMfV7fuRhhK5Rf4R4Hl2Poc5BlYsxINpBd/W
wJZwbRP/IJTEnnvvRxh/KeO2GVgu02eH383JzXn80JDFAbZk6G856uzsiudXMkQnagkx+HohFFdR
/LBcVhw8g/1ZocRMqLSZ9WvYdtAN20JMxufn/f6LGeGTxbdcVgw0Hr+8zuFKu7fYq7FgkEHELeR9
ywFrWEPkdvvykG8CU6QvlSsrihBLDeLPNNn3F/MtgyHk75PCf9VcQL56+GZTIQ6sbDy7MCJtFjYH
aQr6qKo91Wd+Sz/piH5JTY7PVUyb4Hor4CDbJtpqpC7j5FTFOt8M5dHeSbYSiWQ/xaGK5YtlCcfJ
l4jTPKJuJO3WwXVr+7adKBbCrIUS4aeXS9g18eXSvXyJQNosFM901C5DTfC2pbZEevH2vkSI4tRs
tN++OLJKpHstLKgBqKA/yjg7iyLY2zWz//ZIQw/gri0dnOgY6pd5sZRo0YHIj1j4bJflduUbWZjC
FyT7lSr5w6Qp8yJ/dATRhG71yv/lE4gG5e1I/LKDh49SJeH3Vw2hSkhDoIO2MA8PXMXb3VO5Df8W
qRzp5bLm4TmW43lSaI+2Dk4qrAKna262ihyBtjc1k89Xuc+ly0bL80i6Vp77i+qHfNVP31z/CAlo
4d9xktxwIxpaqECf2drxJC6STVsLXxya5amGzMQG0F9xreM7cRbITKYIcE8nswt4+V4m4dyEDRVZ
HpbLW+BZAc/PLzl4LMwVSAzNeMkZHbD3ciVz3HgIPEN+Nave2KnMonjF8CPtUi2zV/MiYz/Cf4Mx
Gwynw/1p/4Cdns0XdG6NM1JpwmM8BiG/mzLYL9pDfBy01LxcKnM8OBqMhrRCpFJtvCROY3N8CLYH
2P0auAaQNscyihDCs0wWWSA8+73D48E6FncihY2ePpYZYc/5febl9lwNTHg8mBB+/uAW6eMD4pEn
ibz3oiRerU1rLc/iFHaNLVgq/RKw4shrKI6Jx0gqYKeCOT7XXIWBVNV7fpe71WEcRXFQJGZzPCBs
9BHDSOVpYXCXpI8RnIBUiYd+eXyP4V7DtBBhYwp+gj9+d3Z+8uFygVDrgN5vhVAbR9KBFDhUyQ8+
93JwOUAeHv+TfkAjhZGe5nfCLcTvC9VnmN4mTdAtGPoZC8gjCuDcfu1MBANNsPr8y7uagaOwxVpo
wUrRGFf4KVgwcHoND9ywAE3qvnsHSRGKED+AP3JIxDWXKayMEME2Ts0j0WUSGyGNKJmvBL9lULGU
w8XiiIGF4igmCmAcBf4BEQSI34v7Ct1eKCIO5tHsXmb/MIznueCKoWpSEDYAr9ngvQX8PGjlvl+L
jBX5SvEQEPSWGXq4RTZdZuzVYq0EeDGAgIuEZ6uCrwTDuwikMhcNWE1ZIgF//DspFZeerkXgpGgv
BAbKVCey3n18G+cijHlPqtUevu1dQtB8ktGni/n1p8noyBt+wnWgxgrRlC0hW62WHST0cU1NJH7B
xg/DDC9vaKNIvwY7mwRSTGiHSZvEKfABT8KQSUNxFweCrXkWJmTkFBDb6KhJRhBXAuB6XZhQYlzZ
r8zIjE0QTAltuMJv58jYCQYpwxQAvDD3OYvdxZz9D3o4TCFP99xITeHVfA0LOTqqlsCQI2StxR0m
vJqggfMcfIEEhGwLMyHRh6iqesADznypgU/M64j+jIKqxANCM4x3Bh4LToG8+hvmXAmmuxCsRht8
foQEjt/VN4yHIbMfSbVlE9ztFtjhGsoWpjgGLucLVAjoXfxWcLphs4KykbE7/CTLdhxJSMS7gNzS
g9AXmGw9MCgegE5hFCm/L+hiDkTUid5kwYLrW3B6dQsx1MPxDxo0gi5aComz1grKUgFeAbN1l1Fy
Yi6J0adsqLmgNY3Vk9QCxQdhaZFB8OAUwj0nrwF5IL6UfICEawSoAMQhb88q1lCrlp2LCIOU7hRB
MHZZbP6BV4wUrQoFpntyxK21bAckwCsoQ9QIyeA5KaeECQPWVh8K1+8T6YNisVgzC2ZUlDAtpWLF
/Y0BhtjcstIn4rFG89pgB5nuY2KMlM2wyLji5kCa9BLF4C6QqSCLZ4QqgjRRUrTmB2EKctqVBDkk
Rgfdo8nYipi01XLKsFxSvqDUbCDf8PD/uQDYxZTsj0v2oUmMJeV/9HyNOAPKgA5p5d0D8AQI7BAt
SjM8bIGsX1PelBnkC4gH4BFj8a9EsKxDm5FQSsXIstOWVOEQB/h6HTc2+JHCNQYslhSa3ns8GWPV
NYOg61wEWHk0qQR5tcawaysBIOWKXNdijvpOTr37JENO6pGVesWVD7r2ApkktvVBf35Sq2Q6ZMWt
YW4NRErKs4JqXJMLqP8FOM1ut4zALa9xbmOzGO0rCXtau2OPXdsCQ28aCoAskrBiJIZ4vc9YzTr6
CMuJcxBw0ncuwl6dk9c9ykTkK3Z1JVSkZFomNFzrxr1mDmjYFIRwptt2hSf8p7EOO8tgXWS32ur7
koIN0w8BkTPsyVEaVt78wVBQUPG1neRh0cXmocaFqEozuzjZnzg+30m7bNt8mHKxNbHLmhgsFTft
BWSmtO8F0H4LK7XzhZIQDlS18m9RLbNMGLRF1SuBayS27vjcQH+PdZ9jWwnlBvzJpS8KQNsJulGb
tXxRVSARVpXGeWw5goGvNgZxd5k3aDgzVhoi65mSFUgrqHnMKnVlo+Yby0poU50zoF0LQMdTj/0A
2wtQ7zE0n+C4p7MPXVgLHPiQf+7j0KxthqT4rtB7hH7KDlwZrgu0JsU0pvbYSQjxtOZJtAddte0Z
QgF+5ggBSet/MmsGZFULG7gaXcnZAwYfNh086drARsIf4wzaNhAL3Ebo8nLnh1k2K+ty3SRjy4GL
6LIAdshZ7rnXZgcEWyLhF6upK/Fv2QBLuzWmxh6Ohsv+TVMeW4uyr1s6U0zZoO7KNNuDHtIU4DB7
q8Cqlq4J125X7qVafbooOzZmr0DaHQpNdd6F0pK9A9ChIQdzSzy7ZMpSGFq5/h3koXMA5BY/6Wmb
k3gLPyRO3AGZBnnQpXnMDYUoWe7V++vF2ZRR0oV/gwI2MxlsZggR3TtAyxF7jnLFXmXhk5axAujb
V6KUlZyIKhJwgk5j0HGGfVdBMJPZwoRehJtGhLtq5IK+DS5TmG085xitKKDPtWgQ2xlAnDxBpcuG
MDB4akCYoLdLMatFkwvyhgVixq2M2/gzAXnJ0sPKby1Jm8Z6N4l5gPYc2KhgNuDJPd9oi9vhafhu
K32TG52kssia+V+79qhkAtlHbNifQ2rGR+iB/nopVwANLe/uxmer6LDB0fDJ1eRdmbD7Nl9YbL6I
MBHRqQYmLDRDhdWedTQyn018c34HNRe3fjFuTwXudfKN24q7UlT1M5QnInsT1unFZbGoSGia1OCq
HkZoHNhKQvsdhftfcAxAW6rqV4nbDhsbGq/64t8ioFNjfankL2Pa2gL1Wdriij8wvq0W2G8EVB1q
d2ibgnz0BnbzhW4sc2bgjcvebqlzO5wPvQpmJDxS8oo8BFdsbEkDvLdnHQk3tNuM15uokvfeY+Zd
9rvnMW2IYfNbCGdet56inuCeBlvB7uCrsOUyLxKHzT1jYdpCvMwoJD3QHjJtT848ciPtGnuwd4bO
UEEHLjvgQdOU2dautChoKCvyKTuy/Z71R8odts1wuADLAa5yBBHpPr7ecyRUAQnGUz8Gx7dT3BmX
3Q9PbS7CrTteLGYWaiuscxLrvK6Pr3IburWH5yltSFVNWtB8ncdZJGs3WEu0PZHsNY7XoA0i/jKZ
bVJs8ilANOhXV4zirsUNs3qYGAZf44yvVlB83Ea8OuLADhGvV98+LY3lB9Hpp/hBfVlXJhNvrwaf
sKNTawCVea401/0fQWVeK+bVKR7R0ZmRSGSOxaoL7yABHoiZshGDviSCPlmAsqE8ZVjlGytcgS3Q
SBCWjRHmTu8bjUQBXac2tsyVac8hRUPZ4ZKM3tINfhl6QjNJDEXHGufsgWPVtS/YtQB+x8S05IaG
wOe1keDhP+OjB6UG9lQA+AUx2lxYNiPNM04Sotw02J1beW5MW7Knjkxph0u1TFPfgGKn0E7EwKgr
9A3WiSoxQE8Mj5kxgqkw1dSm7PzyZDEdvjno7h89DLqjh1F3+GbwJoR6bJPXjlECXiDRHB/22Qrc
XNu38f4uHSnjLaAMFUIfC0+hGjWut4f0RaZ6haKwwr9UgMjpdvIAp7oX/VsSGzGyl/A9e+X/d3sr
314p9APobtbVfDyuzEKuaoD947XyrVBJ9RLFCV2hAtTuy11k8mp0FdaPaQ1eQzxXV6p+1a1vR6Tt
0P7FwKC379hNfXvEWqGA1nGTm1pEw5HjsKGP+eySkOAX1DyAlq9euwGN0J8GuCe230P2kRbz8MPM
sL/fH8Hj6wvcUgeTw0N/4vvBqB+OJjwa8WA0jsJw7B/4+/7B4UEk9uGHvQZKszXqDfVqCUuNl7JK
q7gtvZswQHlvROT2owAleiKKDv0wmOz7fV/w6DAa81BMov4kOhwfikk4HoVReDicED29TmWtWE2R
p9uSxlaXMNnIW5FBPVIV5KPgt5A5rKLoC+aG07cLvGWFE36P8/LvP8adP//8P6/zQNs=
===END CRASH DUMP===

**Comment by Tethered** [comment]
Fixed in the latest commit. Thanks!
