### ISSUE TITLE
Please correct the location of the files on github!

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [Tethered/FactionsPro#40]
Please correct the location of the files on github! You may FactionsPro/src/, and should be FactionsPro/src/FactionsPro. Please fix :+1:

**Comment by flaxues** [comment]
[Server thread/CRITICAL]: ClassNotFoundException: "Class FactionsPro\FactionMain not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

i get this error do u know how to fix it?

**Comment by qwefqwfqwefqwef** [comment]
In the src folder, create a folder FactionsPro

**Comment by Tethered** [comment]
Sorry! Fixed
