### ISSUE TITLE
On multiple world server the /f home is broken

### ISSUE THREAD

**Issue by markkrueg** [Tethered/FactionsPro#43]
If you are on world A and set up your /f sethome, then go to world B and try /f home it will take you to the coordinates your world A base is at, but in world B.

**Comment by BlindTail** [comment]
Confirmed. This is causing a lot of problems because people are getting into worlds they shouldn't be in.

**Comment by LilCrispy2o9** [comment]
I will fix the issues asap for you guys

**Comment by Tethered** [comment]
Fixed
