### ISSUE TITLE
[Server thread/INFO]: $player = <player> is showing in console whenever player chats

### ISSUE THREAD

**Issue by markkrueg** [Tethered/FactionsPro#48]
Testing v1.4 BETA

Maybe some debug code left in? Only happens with FactionsPro plugin installed.

When a player says "hi" in chat; you see this in console:

```
[Server thread/INFO]: $player = bob
[Server thread/INFO]: Bob: hi
```

**Comment by markkrueg** [comment]
May I ask what the fix for this was? I wasn't able to find your commit.

**Comment by Tethered** [comment]
I made a commit yesterday, but forgot to push! :)

**Comment by Tethered** [comment]
https://github.com/Tethered/FactionsPro/commit/de46df0314ca67670e5759f705bbd198dc7258e8#diff-d7bbcb0f8b755350065a7f4fef12ab29L225
