### ISSUE TITLE
/f del faction does NOT remove claims; potential griefing problem

### ISSUE THREAD

**Issue by markkrueg** [Tethered/FactionsPro#50]
When you /f del faction, the claims are not deleted. So a player could go around creating random factions, claiming land, and deleting the faction after. This would leave claimed un-editible land everywhere.

**Comment by HostingItAll** [comment]
added to the to-do list.

**Comment by PIANOCRAFT6000** [comment]
@markkrueg I think you must unclaim the land first and do /f del that's what I did
