### ISSUE TITLE
This is A Request

### ISSUE THREAD

**Issue by devin5411** [Tethered/FactionsPro#54]
Hey Thethered can U add a Admin Bypass mode? So If I'm of i can do /f bypass then edit someones claimed land?

**Comment by Tethered** [comment]
This is a planned feature for 1.4

**Comment by devin5411** [comment]
We need this because people are claiming spawn could you also add a feature where u can't claim in a certain world and area?

**Comment by LilCrispy2o9** [comment]
Just disable the factions command in that world

**Comment by MCPEPIG** [comment]
But faction claims aren't multi world friendly... If you disable the command at spawn world, the player can go to factions world and claim an area,and the claim will effect all worlds, so disabling the command for a certain world wont work.
