### ISSUE TITLE
My server is crashing because of this plugin :(

### ISSUE THREAD

**Issue by flamedrake00** [Tethered/FactionsPro#68]
Error: mkdir(): File exists
File: /plugin-848.phar/src/FactionsPro/FactionMain
Line: 42
Type: E_WARNING

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: FactionsPro v1.3.2

Code:
[33] 
[34] 
[35] class FactionMain extends PluginBase implements Listener {
[36] 	
[37] 	public $db;
[38] 	public $prefs;
[39] 	
[40] 	public function onEnable() {
[41] 		
[42] 		@mkdir($this->getDataFolder());
[43] 		
[44] 		if(!file_exists($this->getDataFolder() . "BannedNames.txt")) {
[45] 			$file = fopen($this->getDataFolder() . "BannedNames.txt", "w");
[46] 			$txt = "Admin:admin:Staff:staff:Owner:owner:Builder:builder:Op:OP:op";
[47] 			fwrite($file, $txt);
[48] 		}
[49] 		
[50] 		$this->getServer()->getPluginManager()->registerEvents(new FactionListener($this), $this);
[51] 		$this->fCommand = new FactionCommands($this);
[52] 		

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1254 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.5 #1 SMP PREEMPT Fri Jan 3 10:00:45 CST 2014 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
SimpleWarp 2.0.3 by Falkirks for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWmlvG8m1/SsV2kCkBzbFVQsHHERjy3kOLIuxaPgBw8AodleTFfU2XdWiOIP57zn3VvVCWZPt
5UMEQ+qu5a7nLlXtX3pWp6o3H00nl8Or8exq0u+psszL3vyXnj0UmOrdfP1y/enj+49/7PV7qTJG
bmk0fYh0eXI6F+90ooR60sYaLIjxhtmzIqm2Ogsup5eDYifLM1OGZ+9kaHWemWWZ18+3UmfYlegM
u6bjX/s9txEkOquxIswjRTJNJpjC+2Tq/87wN0ykMaJDEvJYlUVGLJnaD9IoodMiUanKrBEfIKzK
VCl+IQrnoLC29HTBT0W1SXQoXkeb72jw8miwKFVsePyq3jYddlfEVcZiiDy7yeQmUSenzGY64lVu
x9g//8FZ8bXdaRN8v1X2rbTyXZ5ECqY9JTbTSWfb1D/r+OR3ZOivzuy/sV8MxLr3g8wyFX2UcNzA
Ptl179SLM/O01vY1kRILEeeFyv4lWn0M7kGSBT1vCWIS9Na96yjV2Vzy73sr43hu+PfdHsaf5/z7
h0oTi/nG/70r5nfLeV6se0z1oqEa70tt1QlL2xfEw/G99Ct+pZer1lqzoX9uNbpX5SNpwy8OGrcy
A555rFRbwkV580ggOcnUvoZUjRdnnFPiTn+J/Wx0zCV+k6epzCLo3yHgB72n3MYaAz2A3pYyBLx/
7L0aCoqpIg8flIXZ1HrthA6+D0tpdm+rtDg57f2l39uSQDKhmMC0ARPQGw1mkXoEdbYmwno8myKk
ytzmYY6144t+TxaaV47GgyFWbrXF6/Cf/MGGUj4kekN7BhdMocokpZDeB51VTyLJQ5nscmPFZDAd
zMSrkbi/XYrlp5ub2+VKvCu1+JPMxESMhvPhcD6diTf3KzEejqZClunjRQKKxa4AvdngfDDG28+I
ZLyO8Tp0k19zU/PDAL/AumWuo16TQQxZpptD8OoFPc4sXetNmKGs7C4vDfljpexOlSr6SiZny/1Y
mw4DigMcwtmyUv1epApKOliDOZPH9m13IJXP09p6/SwL5pIUXd7dr77cffrwFkN7tTFAfW+eVUkC
3e45i11DwI4+ncFjdS4Go2N1loyrW+BKrJRMMWl2+Xanw+I/pl8rDKDbFcxrd7+6/rT6vOzq1ttZ
W5j52RmwuKs2gzBPz1pJzzpUYAENw1kVWleivAU6g10LTAYjeWyAD2//70jTq39fUZBar1vG6/U/
4cWXNAWd4PbN8uaso0Tj6S+yLL7xNA929YS7BpNjRd/J5EGXD+b/6VfQMXZVyszEquy1ysee/Hpt
WKQ9RKr97cX7h2imUJUlFEPOrZlzrhsgYRWqtFpRZL9aNm/iTZ7FeiuoBKzLdfZqVSnxpyoR40sx
ms6HV0hw4vPqDaWTGS1w9AKy3uJzgixLCRnyifuqfNSPMuksKvLSLkZXo8mYBrfYkqLnWAzpLZVP
QZHIAwRdeMqF3GdB4TwGLyyCEQ3vd9AvQblY5HFMA87UwU+VKg+LPOsMlSF2+VWRMmGpCybk8r1I
ZaREZXS2FW0sBLdLFie30eKLSgAfJZxcwuaCaotw2vyuoxi1cYssL1OnLulVHoJEp9ouzqe3NIb+
yQZVEUmrapFQ63O0MsrrHchwp9Wja6C8Io9a7YMIykqsW7BZZJLk+yBO9HbXmMCZSmYaAtRb3Via
b+oB9IhRmJcN++Kx8DORjmMdVok9LNjErvAhSgKjrIV9zIJVgHDJP/C0W2OUihZxgpURapkaDtsp
NtXbm3fXnz+saJR8NCjQXO7zMlr8D/9AycrmgZGPykvITg+6Xo/zEpZrMORHqXg1hX1wSBNCt+B+
NWRgV9CLWkduyECj6/l7xCUQL1Y7hWa2Vh01U8HvCt0mwsPupBUhec6KDTreLEyqSEV4EN9EFtG6
J/zkMRF4TtPIGF1WTtXPEEmxKZV8EIe8Kj0toWMB7XSsmQOcVyIUkgMR/ojWpyZ3FqlYwn1G7PPs
91bIolDwCxkxhbroFpIDxHfoZc33O5WJqtiWMgKBwTojKDti83UmXq12pYK9MQQpEpltK7Rwgk4I
bDQPe6Pxzt2I/pnNSlvf7FTotTjeCAHq3KyywV4/6EJFWg7ycntGb2fUA37N46/v7+++nk+ugvFX
2gczNoTm6HhVtl33iNGXHXcOFJYGuVRAS2Fsyfa1lE8TxFrkptmaLCnkwJOy7FJ0cjpUYofWJmEn
pyDskNWyRCI2CuNmV9kop5hyJzQSxmeSMMmNipxY1xSfgqBKicV3SuJRS/FnylBYwpkq8DNzQRWC
Nt7vsE8STk0OaTwX5yrpCSFdAYSoJgACa3e9fI+VqEkR2amdCCDWBkK15N1RqaZD/TMlAwG4AhEk
6uYgPI6w3GfQZral80XDznkGRMkoEqUyDngkJaD2AGmkqUrOYgJw2ygyB2yufqpkQt7YanT/AvkC
leXEc0Q5OQVxxw6JW1GpCODMLU4Oc4GCAM4fq3QDYyOars0hC1fSPADw5QPiZ0Dzn+EDhmetI63a
lTmyLBCB1aZP65NI+AQHxPZhhRRGM1Tn2SqooDSWVhkCh5Yw7XtGDPRBbJX5ExItitCB1GGkZ41o
ZFQnzvuYApSWUCD2hba/h+VsybsiRVWNQfhsrziBBnCzGJNFWIfAazlnShSsrsJwqP4xyTcwLDUV
wg0LLjyUklK1lZuDhUDi3okyZObakHddoEOnvWbB2NiCqosvYH7IsF1iDbQgSyk6uxGVGCmi5ujc
v6NySpjd5tAjp8ggm4HPloV0FXEOZ08v15wsODNbJBsZ/ZdrQF1ZLf9oOJ46+Zeq1Dlnf8K+IaIh
5z9PtcH3CFhAZEfkU14RAH+KTOEIoe1CvkBEQEgKxt/SwcmOcphwQqXYcsvWXOGIBtDeRo6LWuJw
RyFLBYWXD75dTNHq21YYu1Ah1R3DNiFZnTfc3kYBJFxVmFbNydDraU5fFMhrPXFab2W5gbEDHJwT
1+MRol+0KvuORPF7hN+TUxuXVVzhulKg/ldAzWm/jsFnsPG4cXksjutYTFs8DsSdKy/8hq5vl1dJ
1AiiEbH7TLSiE0hEwZJDwXOc5FlH8eodw+6bXMRYcbsbpeIyT+uURnv9fNDNAh2fQgnvuudQeAE/
nX3Ua4e7Knswzt4fONooAfEgSUZHC9LG9759joUS9d64RQGVXGodWlpEqnazD5Srcy/n29xte+4+
d4tXb+tScFz8sv+Azpz4gxA9tnJaeyzUjGiiKXJ/l9Q6y5QlXzSdEqCRuMqzkRZNPNV9SW0lCg7w
5PMXB6DrA/2sS1sb1dQg9BB1rfGIrWco8MuDJdp9EYw6YKZaw2wDW4uCtDI7d1mlrW3cflNhiVyu
8w50ezHoZRqI/8XJAuZdoPUEcN8sP/exFxJskH/2OrI7lyI5vhvyAZOfiwtfiNsSbdgwnaUDcR0h
nnYyic/QU7uuIVLAmWcElg5/edYNyKYadmi13dmrmycKPmo7ZNJ3gU2Mv+gMTRvUAmwUQ5tq6+dl
tqwrc9siU9NBm3DUJm5VkRWBf+UWyPOiw+Sm2s59kf9ejKi4O2caauJ4um7gDOexnaobu7V3BcpI
25YZcYYznq0AmLNt6EzL15kt7OqT1VGXruqWjcSGIu58wks9ukhb9ncIG1oGmN8SuC1zkYZ0L+u6
d+jDNxYkLRAHjHJOkkf0kTjp/GM77Pls/I00HKLsuVcf71Y3c8FJF//CCkeZDEcZJtR8N2DxPOdG
vMbD10fOCtG1I5F4XRlEXJEgCYHGEnDGQ19BKJO5wkQoosMljftq5IP+eLhOYTMfka4QbugzR8vr
ZIQweYFJX4wxMXppQtlwcMoha1RXCAbDiijTOcbfhAiFtOT4UeF3juQTY3uUpDTARw5qVCgZyGQv
D8bR9nRaFB0lbwbRdZpXWTf7G98d1TKQ9ESM+nO668AjEsxvb5UlRiMnuqNxXHLE6Orl3YytTLkz
20Y5ahsVUxri2wxKV+SFhqq74+jkPZf27uUjKi4d+zQdTRUddYqDP4b7QtR0M5wlYkmfJeqc6HNY
XCW8LDcAakDxqUNXR/i8U9LZF7gA2dpUf83p2OEiw8iUoJJyoqTq0ujfpBHnDDJo7Yxb+STkc7vg
wBFycWjhcOSLIe38hJN8ZTq7vBtk9/bK7fSoo/XoVCgf0V2Sv5xq5cOpVknHg29evhG8PUXVsg++
Fd4nv73UfB7G2bdS3r9+Pwc9jwcGzpqLy3+LWpEXVeKp+WeqS88IrzMOyQDWI6HdlVnAOILmU2ra
4PCM0NCMjnxyoPuouXCdXe1SmCirCnQ6rt1zgOTU4boMTwtULmiXZ2j8kRaKEKNmkMdkutFAvlvi
r8LcgXjuchEd3elLlXCjrsB6kDj0+ja+SW2E64AuU45HmmJyNFrsCp3FeYsD+tQ0dywHnds1dEEs
X5Znh5R6fI4QA/uaRlA6tPhp0U6zwACbFHK7Re3xJ/HmioMaRPpe9/CyNk4eImdekofs5bDMLn6+
G5hws3PngDILfGVu2z8ezQvzjOV+v3+JYaKRy53ON0+Sapl7oV4AaPUfEebCP/AUoGRsDuD8SI8B
MjhOKhj4C1F0OaYu8d17Qy7pdSvuzkP1XS0fdF66huRzI5cIw9WYAidFkdYQ1JfPjujMlQXgJ0FX
uRQYU35ruM3Fuw/Xq/n4u4v+7Opp1J88Tfrj70bfRShzLiecWJyuQ4rfxeVQbIEe496ms1O+qOX/
QEAG4e+Ib5DlO18kyUGdVyTbbW/OgOz3ipCW+hfzU6KtmriPpYH7NPuz+3rqvr5uQvQMu2Y9XQFm
kSzbAfd/MOq3qkyal1gnABGTHo2YWGyLZnabts87xAZ/D6RFfzX+4+CYPw6mG3cr2SxGv3UobKuB
lSRQ1FH3fvmBudJzEaJPavceoDB/rPVPYjYg6UhzEdBXmfFwNpzg8fV7+C2eXEyUnEXRbDa5vDgf
TYfn8nI4Hsvp5lJOLqbT0eVmPB0q8RqcljsyC3/qYsa50U+t0f052C8YkaKfVOwPcRhlfpdqFocS
XeAUbIfxxUV4cXl5PpuB9eRqPFGT4ebq4iqKmJ/ZpXlrQsOBZY411c74WGzzB5Uhi5fNyBclH0oV
O0MNZhg5SL7wHw1GvOBnXdSf4ae9X3/9G6S2Tc4=
===END CRASH DUMP===

**Comment by flamedrake00** [comment]
This is awesome plugin tho, pls fix it thanks

**Comment by Pub4Game** [comment]
Use the latest version of the plugin from github

**Comment by flamedrake00** [comment]
How do I download from Github, i'm just new here

**Comment by Pub4Game** [comment]
http://vk.com/doc194328500_409733288?wnd=1 

Good luck with your server

**Comment by Pub4Game** [comment]
![default](https://cloud.githubusercontent.com/assets/11244874/8958974/ca3c2f6a-3610-11e5-9c0b-8a137415f8bc.PNG)

**Comment by flamedrake00** [comment]
Oh because im using mobile

**Comment by flamedrake00** [comment]
Do i need to install factionspro again from pocketmine then delete the files

**Comment by HostingItAll** [comment]
As above, install the latest version from Git.
