### ISSUE TITLE
[MAJOR] Case sensitive issue!

### ISSUE THREAD

**Issue by brunyman** [Tethered/FactionsPro#69]
Hi, there is a major issue with this plugin, if I brunyman have a faction defined and a player joins the server with this name Brunyman it's seen as a different player by the server but not by this plugin and he is seen as a faction member just like the real brunyman player.

**Comment by HostingItAll** [comment]
Please install an Auth plugin such as simpleauth to correct this. names must be set to lowercase for many plugins.
