### ISSUE TITLE
Call to a member function isOnline() on null

### ISSUE THREAD

**Issue by alicheek** [Tethered/FactionsPro#73]
Hey there first of all want to say what great work you have done with this plugin really is the next level plugin from all the other pocket mc plugins, keep up the good work! :)

Here is the Crash Report:

PocketMine-MP Crash Dump Wed Aug 26 21:17:53 BST 2015

Error: Call to a member function isOnline() on null
File: /FactionsPro_v1.3.2.phar/src/FactionsPro/FactionCommands
Line: 138
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: FactionsPro v1.3.2

Code:
[129] 						if(!$this->plugin->isInFaction($sender->getName())) {
[130] 							$sender->sendMessage($this->plugin->formatMessage("You must be in a faction to use this!"));
[131] 						}
[132] 						if(!$this->plugin->isLeader($player)) {
[133] 							$sender->sendMessage($this->plugin->formatMessage("You must be leader to use this"));
[134] 						}
[135] 						if($this->plugin->getPlayerFaction($player) != $this->plugin->getPlayerFaction($args[1])) {
[136] 							$sender->sendMessage($this->plugin->formatMessage("Add player to faction first!"));
[137] 						}		
[138] 						if(!$this->plugin->getServer()->getPlayerExact($args[1])->isOnline()) {
[139] 							$sender->sendMessage($this->plugin->formatMessage("Player not online!"));
[140] 						}
[141] 							$factionName = $this->plugin->getPlayerFaction($player);
[142] 							$factionName = $this->plugin->getPlayerFaction($player);
[143] 	
[144] 							$stmt = $this->plugin->db->prepare("INSERT OR REPLACE INTO master (player, faction, rank) VALUES (:player, :faction, :rank);");
[145] 							$stmt->bindValue(":player", $player);
[146] 							$stmt->bindValue(":faction", $factionName);
[147] 							$stmt->bindValue(":rank", "Member");
[148] 							$result = $stmt->execute();

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1258 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux FTB.creeperlabs.com 3.9.1 #1 SMP Wed May 8 20:03:43 BST 2013 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
iProtector 3.1a by LDX for API(s) 1.9.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.1.9 by 64FF00 for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SimpleAuthHelper 2.0.0 by aliuly for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWvlv28iS/ld6lADPXoiyTh8KHMDjOO9lYcda25nsIhoYLbIp8ZnXsEnLmkH+9/2qunnJTuJk
8sPLHBH7qPrqrm7yr04eRKozHYzH/f1hf3gw6nZUliVZZ/pXJ9+kmOqc3Z5dXV1edbqdSGktlzR2
KsNQ5ImQIlLRQmXCL2I3D5JYBPoyDoNY7ewKPMVFGGKjH4S0a++t5EV6liW394PeqDfspSuZ7enM
bc6Vv0+TKJKxp0GBSALm6PBzt5OGxTKIQa+xBUvcxFMEezA8wtw8r/8J/J1fXuarQDuvzV7ndaDf
xXb7zkutYk9lzuulyt/LCNB3d8VfoDgY9bcozfNqMf19YRSys0XcT7JI5uXkvPN/SSGiQudioUQQ
Q2m+4UwaLLQStPuXeWd39xUzHWwx/cyjw+cIda4kwO28TEO5UVklxuinixEyo6YANf7xk/gnj/Fv
8YP6Z4y7MowVQ/xyLL65VmZL/WnweyXz/k+R+cTzhEFBspZ284NM5w2LHWxLTP/jmcNvWw2iXKvs
Hmbbbch19gBetVRk3DKwSgmPfoqEhp2IkxwBSwxqucb9pyw5HjzmaxVD0SOeYStrV8Nk+HPJGV/n
n+MnFJRH+WOS3gK/M5XKjDTy7v312dWNuLwSV2ez85PTM/Hu/c2liKTOoagdw61bOkNXZDK+2xW/
nZx/OLsWO9NyflotmPKKV9CrgTh5GpfzehHE3m8yLAiFpTPvdEVbwP1n7bbMeXtDnZbGwbNoEGwi
MO9ccJavBDh8vD1TughZtYaQelBukcNbX3WQsvNMukjOnzov+mJndyrSxL1TeQRvm8+N8zuv3Uzq
1ZsiSnd2O793O0sVq0yGlNExrYEfTAe9iafugWFRBKGHgjCcHKIgZEmeuAnWDg+6HZkGvHIw7PWx
chnkeOw/8w82ZPIuDBa0p3fAFIpYUo3snAdx8SDe3vzaczOlUpWFcqF7bhKJUe+oNxAvBuL6YiY+
Kk9cyI04FMP+tD+ajkfi1+sbPAxG4uFw/3Z/DJrpKgXFSW+/N8TTnwhXPA7x2DeTt4kuOWKAH0J+
qOqfJs1cB1EaqpMiX9GTxdkY7LZ0d9AbYERiIsk0WWPGZriAGcSNkhEm9SpZrgI3JQuwIj+VmsSA
iuUiVECaZ4XqdjzogKrz9BPmdOLnb5oDkeQaXYOBpZvAwkSSzNc3J1c3H2YYWKuFDnISYJXnqZ7u
7cF0q2JBGt6rke41qEAZMwXP8ovwOpXruKGE9nhDD8PeuKWD8zf/2xJ2xEoa9MY/LjNIzuctAPP5
BU1VUs8ur28+Xl6dv2nKTc0SJArQzuTKzU0TZsVpDDZtCrCy81Vxjv6mGDXjZ8nwlO1Ax7k4nZ3t
NYSAnGduEifR5mT2riFnY7ApJxywd9gWNInVAv+1hO1z+MBh7d/D6m9j05F9btrY/D34USVZGPO5
MsiBZT5vSfEMk8+KTM1UFummA1dj7SCGSduK2B+/fdvv/7SAvTX04MAlgMbP749b2mny1V5NhUTm
gP5nITOvKXRjtG3/wXbuolyAkuGjJv/37H1b/P6Pi98mC9FbiL7X9dvU9hrE9kgJpysJED43bQ0t
tIa3rb+lhrcyvAuyO91SwP6Py+9bevO5CxSeRTGfb2F6hlM/XBWh0g8NucqRtkgmaBsiPbwN0Yi1
BDr8cYEMtfncMv+eTGzD+HqVpI9TFI9u56j9b+eob8ZmMwd+R+JB5U6rzGPBPUPGXzOscbm1bcjY
HN1ywC0Rz+6T8BoQf1r+abDettWXcg5ibr1e9xSgENVefkfBhROOivNAhvpm1hCtNbwdXG1P/Fki
NVnCXm0Az7BR856jFqR9+9GUY8RNZcNINypfqUx5tz/NSg3m87l9eH5g1S3cv1SYtjzv0dR2iG0l
CxkGRbj5zghrtJBfkdGQns9XDOR7EsdvaHOu1Lpd2xqDrXZ08NX+7Ustzehv9nU1mh/JiCoMn8iI
ii/7/nMyIvDUGdGAe2YzRtVuqxfjoe0463+7FRt8S7i6LXokWyvGv9CiEa76199u0JjIZzplygzC
IwuX3sTH9B7O2giGPFB0JH0xq57EaRL7wVLQVe88m8cv6Bh8UizFcF8MJtPR0bQ/LM/BE1oQJbl3
/GsWqIx2N06i5j6AlhiWTppk+fHgaDAa8j4VJdnGCYMoyI+H/f3xBY2uV5AQgzo/7tOzjOOkiF3l
mKsTR7qrQN2rCJlXHye+z+TpZOak5kwCLR8P9pmBfLC79PGgb6iFYbJ2/DBYrvL2bhkHETL5cRLX
Y1GyKAeWkuB6yoDykwyIqjGzZIUQdJNMlXTT+9TOeIHvB24R5pvjERPjGxGcnhyt8jyIl/qYhkPI
FTrkqcfrJAu9ekwr5TWW0H3+8Zuztycfzm9o1Lik80ehso1laYcyxEyJh373Uqk1iHvH/8V/oJEi
Txwt70sp6NaiutPpbaKQvENQYhEuO0YB5ObqNFQCimhY3LmYwV/EzUppJUrRBJo2gaolENEaP2Qu
XDKqvUR3w8KDg4H8I78kWtdJhJ0+EdimqaWvuiKhgqiJpFhkSt6JTVJklpYIfAEDBX7AHGCcDA6C
SgDC79W6IreH7ljCPFqsk/gfuZBpqmQmSDURhHXhNRt6CUJ3jUbu9UrFokiXmfRAoDePyccNsek8
Fi9uVpmCF2MIKEIZLwu5VIJebLDKbDzoAM9hAvrBn6xU2nq6Uq6Vor0RAMqwV3FvHdwFqfIC2Uuy
5R497Z0jaG4T//bd9eXt/ujIGd7SPqixIjQVc+Sv5bxDjD6uuJmg63C6ZRb0JkjnGes3z2SsQ5lD
bzzN2mSkwIFfKmeTeuo+cJVYydgL2cgRCJvgqFniIKIVxvWqyL2EwspcWRMYkyLEldK5zEh9BtoJ
hamgJIAhYa/JxH0gxf+Qj2MJ+7pjZ6aCcjFtRLu8FpI8VSdAZDkZc0lLiF50aEBP4QwsIaoRViL3
e6SresIBtEWiVU3+jKOqpAOpBQW8gMvCKwjqYiOsL2G5jcFqtlbFi48BlJ3EcCvpecJcuWoDE/52
BzhSI4dTlhPwuYUifUDx6o9C8vu6ZXCPtfd0wSt2LEtk5F0QN/wQ+4ryrQOLLpcqm2KWOL8v+DUf
QupEb2L3Ruo7eH12hyDq0fwHDY2Qj5ZC0qpVhtJbwC2wWncFZydhsxhfjKMAQWuaCiqrBZWKxqIi
RvTQEqZ9zW4DeRBgWfKAhJsrqADisLvHFTTSqoHzzqco5TeUiMauCPJ/0AvLjHd5ihI+e+LWXrED
CeiF1pA0wjI4VsopU6KINQWI4/WfYbKAYqloCzMsuC5RXorUUi42OQCJawOlz8wDTeY10Q6Z1gED
Y2ULqjK2vtkhzXrxA7gLUhXSeMykfOSJkqMxP4Qp2GmXCeRIKDz4rVwslgzSFMyp6M85XXBmzpFu
pPcfDp96nq+Ap/L5t8DrPEmZv01XFR5LTQuEFNU/5ZVoiGcJadQfjg0q9HBBwiWJYlETQ5eTskVX
xdsArJBqPPIxXuEgHpSJNE7lCY6HMSIUeqPs8CW1GnWi8wk5y1Osm2VzLrpEA9FXR7JJR8ThklII
VTle3nu8mMS2HStUmCqXiqFmtRBWo2OztxIAmlSprsUc9a2cevdJQFbqkZF6KbMF7O+4SRiadowi
7EmtsjsRFLtH2D2I3UjGBZfdJgq0JAV8Ybdb5oQtZ7DeYPKq75e5Iaq9rCcuTc3jJ3jEKilCrwIS
IIOsY1FDJ78VKSOHgPv9vpFRvHjLkfAoN7KvmN2VUH6WRGWKpb123mlmpYZNIYQ13bYrPOE/jX3U
7bqrIr7TRt/n7PWUEHmQkNGBgqQR5ZtNCs8MTYg2ixzqA6ifqWkRqdLMNlCO9i3ON4nZtm0+KgLU
LZltTQqGi132E2TmQuS4OBMoI7X1hZIRTVTV+6uk5nGscrJF1b7BNUJTCRcyx6GDGhFJnS4KIPzJ
ZiUOQNOc2lmTjBaqqomcbl4001c5Q4GfbXKi3RXOoOHMVPuYrZOXUJBWJvsmq9S1ls8DVOg8k+6s
Ac1eDFpMPfEvnHig3mP0w3Dc09mHLvYCwQL5Zx14+cpkbY7virzD5KfiwDYGdcugWTGNpT1x4iGe
VjL099Domy7GU/Azywgsjf8lcTMgq+rcoNXok84eKPioDZJh1wQ2Mf4YxOgkIdYNnzntxysfZvGs
7BTqvp2aINrENyTUtMepYx+bPRlOaWpRLKe26XgtBtRs2MpCXSVPlx2l5jy2UmWnObemmIpB3Sdq
sYe2Ni/gMHtL16iWP4NqMC3Pd62zgyqbSGG+8TCnJl5q3YvEZYO7UGLOHma3OGbLVESYWtozBQTi
2wqCC5eDk3JSki36yJx0Kssb7KHM/DEajlE23Yv3lzdnU8FZF/+6BQ5YMQ5YTIiv5sh0DM9yruBV
Jj5pWcvFWWKpSlnZi7gkAQl5TU6eM+zbEkKpzFQmciM6yNK4LUc26tvDZQ4zvfA1hSsJuJBaNZjt
DBAoT3DpiiEmBk9NqNzt7XLQatVEwe5wQ5TpeGVvI4RCYjL8qPQbS/JBtj7hUiLgUxB1T5QOZLiW
G21oWzoNP2rlb3ajkygp4mYB0LZnK0EQfKJGRwbkZvo5FeMvb5UZRj2D3X7S0qo6YnA0fHI3e1es
zFlyoQy1hfIpE/FFC2UsMkNF1Vy/NFKfyXzX8h5Fl/q7gI7Mio5f6cZeD9haVDU0nCh886mP1YtN
Y34R8rJEw1UdCtHANaWEj2AZncnhGCBbqurfCZ2ETGxo+paJPrYkp6YCU8m/ZQxSaGmMC/kg5LZe
cAZyuT7U/tC2BTvplfSCQje2WTvIxudsdqv1O1qPboVyEt1zOUXqwRdrgMINlTRM+KKtroIGeH2w
K7H3HoO3+W8tAz6j4zxeKGtfu5/DnscdDWNNxeEPUUuTtAgtNfubStMW4XnMMelAewTa3OY57Eea
NEmqjJCrc7p2saMDmx7o9msqTHNXmhQaiosUzY7p+IxDcvIwjYalBSoHtMsyJKITelxLYlQN8piM
FgE83yyxF2/mjD41yYiuE+jTKWFGTY21TmK813byVXIjv3bokqc9UpWT1mi6SoPYT2o3WCVke2bZ
a9z5oRFifHESbyJq8zlCNPSrK6B0brHTop5mwPA1KeRyiepjLweqaxfqEekDsrunpTF4iJx+Cg/p
y7gym3h7N3zCzE6NAbLYscW57gB5NEkbF0andG/IF1kqTFKqVl08QwK6pcvLVgydiY9OWUHZqE8x
1XlaZEtrQdZBPDaICPt2odFDFGg4dW4KXJnwLDWykJku6estpdBb0SdUEgYoN8YqZw+S6q15oIYF
9C2IaYmGp+DsdFKeik/000GR6fLR+XeiaLJg2YY0b1xZiPK8YA5t5S02n8aeusDlwy1XMc0dA4kd
oZEIANSW+AZ05soA+JegS28KXS5JNbepeHt+cjMdvjroTo4eBt3Rw6g7fDV45aESm6y1k2cKD8gw
x4d9sYR/a/M0nuzyBbd6yFVMCuHPdE5Rhxqf8JELNR5RDpb0ESZCpttJXVpqH/QfYZCrkfm+0DFf
M/5pPjg07/YWLvqaVbWeLk9jT2b1gPkuv3wqsrB68IOQ3+OD9MC8MPTztJpdRvXvFaLXfH2BRf/W
9oWW+U4qWpj73GoxesJNmtcS5JIAeQ1xr2fnzJV+py56uXrvBgLz1432l5j0CB1JLhx6GzTsT/oj
/Hz5DnbzRwcjJSeeN5mMDg/2B+P+vjzsD4dyvDiUo4PxeHC4GI77SrwEp9mK1MKvGZlxooOHWun2
sG4XDEjQK+XbkyZGmd+hmviuRKc6Btu+f3DgHhwe7k8mYD06Go7UqL84OjjyPOanV1FSq1BzYOm2
pIFRPhbnyZ2KUWeyauSjknfICEZRvQlGNpJflJSf9fwZpOWXq+PO58//D7sV6io=
===END CRASH DUMP===

**Comment by Tethered** [comment]
Use version 1.4
