### ISSUE TITLE
Little question

### ISSUE THREAD

**Issue by Taytan9912** [Tethered/FactionsPro#74]
How i can hide this stars? You know, officers and leaders
thx

**Comment by Taytan9912** [comment]
I mean ranks

**Comment by Pub4Game** [comment]
To edit the code of the plugin :D

**Comment by Taytan9912** [comment]
I changed this in listener.php and still doesnt works

**Comment by Taytan9912** [comment]
What i do wrongly ?

**Comment by Pub4Game** [comment]
@Taytan9912 You use PureChat and clan tag?

**Comment by Taytan9912** [comment]
You mean {faction} ?

**Comment by Pub4Game** [comment]
Yes

**Comment by Taytan9912** [comment]
Yea i have PureChat and i set this

**Comment by Taytan9912** [comment]
This is piece of my listener.php


}
			return true;
		}
		
		//Member
		if($this->plugin->isInFaction($PCE->getPlayer()->getName()) && $this->plugin->isMember($PCE->getPlayer()->getName())) {
			$message = $PCE->getMessage();
			$player = $PCE->getPlayer()->getName();
			$faction = $this->plugin->getPlayerFaction($player);
			
			$PCE->setFormat("[$faction] $player: $message");
			return true;
		}
		//Officer
		elseif($this->plugin->isInFaction($PCE->getPlayer()->getName()) && $this->plugin->isOfficer($PCE->getPlayer()->getName())) {
			$message = $PCE->getMessage();
			$player = $PCE->getPlayer()->getName();
			$faction = $this->plugin->getPlayerFaction($player);
			
			$PCE->setFormat("[$faction] $player: $message");
			return true;
		}
		//Leader
		elseif($this->plugin->isInFaction($PCE->getPlayer()->getName()) && $this->plugin->isLeader($PCE->getPlayer()->getName())) {
			$message = $PCE->getMessage();
			$player = $PCE->getPlayer()->getName();
			$faction = $this->plugin->getPlayerFaction($player);
			$PCE->setFormat("[$faction] $player: $message");
			return true;
		//Not in faction
		}else {
			$message = $PCE->getMessage();
			$player = $PCE->getPlayer()->getName();
			$PCE->setFormat("$player: $message");
		}
	}

**Comment by Pub4Game** [comment]
If you are using PureChat and tag {faction}, then you need to edit PureChat.php

        if($this->factionsPro != null) 
        {
            if($this->getConfig()->getNested("custom-no-fac-message") == null)
            {
                $this->getConfig()->setNested("custom-no-fac-message", "...");
                $this->saveConfig();
            }
            if(!$this->factionsPro->isInFaction($player->getName()))
            {
                $chatFormat = str_replace("{faction}", $this->getConfig()->getNested("custom-no-fac-message"), $chatFormat);
            }
            if($this->factionsPro->isLeader($player->getName()))
            {
                $chatFormat = str_replace("{faction}", "**" . $this->factionsPro->getPlayerFaction($player->getName()), $chatFormat);
            }
            elseif($this->factionsPro->isOfficer($player->getName()))
            {
                $chatFormat = str_replace("{faction}", "*" . $this->factionsPro->getPlayerFaction($player->getName()), $chatFormat);
            }
            else
            {
                $chatFormat = str_replace("{faction}", "" . $this->factionsPro->getPlayerFaction($player->getName()), $chatFormat);
            }

**Comment by Taytan9912** [comment]
Omg thanks! 😀

**Comment by Pub4Game** [comment]
:+1:

**Comment by Taytan9912** [comment]
When this finally working then this remove groups from chat ,_, 
this look like -> <faction> <nick>
before looks like -> <faction> <group> <nick>
What i can do to fix this ?

**Comment by Taytan9912** [comment]
And colors gone

**Comment by Pub4Game** [comment]
I don't understand you( do You speak Russian?

**Comment by Taytan9912** [comment]
Just i use bad letter xD
this look like this: [faction] playernick -> message
It should look like this: [faction] [group] playernick -> message

**Comment by Taytan9912** [comment]
I mean character *

**Comment by Taytan9912** [comment]
You can send to me fixed purechat.php ? 
Thx

**Comment by Pub4Game** [comment]
What is there to fix? Just go ahead and remove the stars

**Comment by Taytan9912** [comment]
I do it
this doesn't work

**Comment by Taytan9912** [comment]
Ok now its work, i fixed this and thx again

**Comment by LilCrispy2o9** [comment]
Due to the 0.12.1 update coming, these plugins are taking much longer than
expected your skywars will be fixed ASAP after a stable build for 0.12.1
