### ISSUE TITLE
Missing isInFaction() on FactionMain.php breaks PureChat

### ISSUE THREAD

**Issue by Awzaw** [Tethered/FactionsPro#77]
That sums it up I think... up to you 2 devs to work out who changes I suppose!

**Comment by kenygamer** [comment]
**getPlayerFaction()** should have an **else** statement in *API*.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Awzaw** [comment]
Until Tethered returns... PMMP have released an updated version on [Poggit](https://poggit.pmmp.io/p/FactionsProBeta)
