### ISSUE TITLE
I have a feature request amazing

### ISSUE THREAD

**Issue by PIANOCRAFT6000** [Tethered/FactionsPro#80]
@Tethered I want you to add /f mail invite <player name> if player is offline you can mail him and if he is now online he can accept it and sometimes you can also add  /f mail <faction's name> <message> so you can also mail a faction and also /f mail read. I like this plugin very much :)

**Comment by DRedDogPE** [comment]
Im gonna see if i can do this but with /f chat instead. i might try /f mail after i get /f chat working

**Comment by Tethered** [comment]
Great idea! This will definitely be added!

**Comment by RandomAltThingy** [comment]
Or just do /f invite then when they login it will show...

No need for a new command.
