### ISSUE TITLE
Server crash on /reload

### ISSUE THREAD

**Issue by tankisu01** [Tethered/FactionsPro#87]
Crash happens after reloading server (/reload)
sry for bad english :(
PocketMine-MP Crash Dump Sun Nov 15 20:07:10 AMT 2015

Error: Call to a member function getFaction() on null
File: /phar_FactionsPro-master-1_S2kVbKexVcPyW29.phar/src/FactionsPro/FactionListener
Line: 44
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: FactionsPro v1.5b1

Code:
[35] 		$this->plugin->addSession($event->getPlayer());
[36] 	}
[37] 	
[38] 	public function onQuit(PlayerQuitEvent $event)
[39] 	{
[40] 		$this->plugin->removeSession($event->getPlayer());
[41] 	}
[42] 	
[43] 	public function factionChat(PlayerChatEvent $PCE) {
[44] 		$faction = $this->plugin->getSession($PCE->getPlayer())->getFaction();
[45] 		if($faction == null) {
[46] 			$PCE->setFormat($PCE->getPlayer()->getName() . ": " . $PCE->getMessage());
[47] 		} else {
[48] 			$PCE->setFormat("[" . $faction->getName() . "] " . $PCE->getPlayer()->getName() . ": " . $PCE->getMessage());
[49] 		}
[50] 		return true;
[51] 		
[52] 		$player = strtolower($PCE->getPlayer()->getName());
[53] 	}
[54] 		//MOTD Check

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #48 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux s2.24serv.pro 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ServerAuth 2.10 by EvolSoft for API(s) 1.11.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
FactionsPro 1.5b1 by Tethered_ for API(s) 1.12.0
SignShop 1.1.2 by xionbig, xionbig for API(s) 1.11.0
ClearLagg 0.0.1 by LDX for API(s) 1.8.0
SaveInv 0.0.1 by Pub4Game for API(s) 1.12.0
BanClient 1.1 by luca28pet for API(s) 1.12.0
AllServers 1.2 by hoyinm14mc for API(s) 1.12.0
Rainbow_Effect 1.0.0 by LilCrispy2o9/Angelo Vidrio for API(s) 1.12.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
BanItem 2.1 by LDX for API(s) 1.0.0
GrabBag 2.3.0 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
Fly 0.0.1 by Pub4Game for API(s) 1.12.0
MineReset 2.1 by Falk for API(s) 1.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
RegionGuard 1#edited by Asyv3n for API(s) 1.6.0
SimpleGamemode 1.0 by MamayAdesu for API(s) 1.2.0
BouncyBlocks 1.1 by Darunia18 for API(s) 1.9.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
ChatScribe 1.2.0 by aliuly for API(s) 1.10.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVWwtv28aW/isDpcCNF6Le8kOFA7iO05u9TqIbO80CVWGMyJHEmuSwHNK2WuS/73fODF+Kkziu
d7EbtAl5OHPezyH1VycPY9WZDSeTg/3BeH886HZUlumsM/urk29TPOqcXZ29f//ufafbiZUxck2w
UxlFItdCiljFS5WJVZH4eagTsVb5K8mXz/cE7pMiirB1FUa0r59uZHblFph5pr1Ymlxl3vDqYnT9
y/Jf6u4Xf779ODrq0cq+yfx+Y3V5fR5iU6IyII7CBIgnk0/dThoV6zABlcYOrPB1oEic8RSPFvki
/yHfhMZ7YZd7L2QQXEAw4vgHdaOS3HsBIeaR3Krs+d7ej0Ax3uetn+jygC/p6pCv0mIZhX6tAJ38
uwjz53Y/XZ4RTmFR79G+I973Fy4ng/tZylSsb9S3uJoMK64mo5KryfherlZWJacbWbJGl461+enZ
nmB+JiU/br04FjusgYmKL+xrc8V3lfmZx1Lp4ep5jfSY3cLR3HcrQJURGqDQWQxGPyPAN29lrOBb
PbHozPA/Lqp1b6yDlvo5cJg/CRUZZakdfpHaovOrxebY3CX22w6xRzJ1VDKFm2lp/0zlRZaIPCsU
LZoOHZyuR6VNUiYIk5g8y3Wkb0H9a9wwvem4cpJpad1+/827y5fidKP86w4CJ8+kjxD5tfNsIJ7v
zUSq/WuVx4isxeJCZTeIzxd+Js3mZRGnz5daR0ome53fup01RaGMKLywirwCJIa9/UDdgOCyCKMA
wXmI2Mx0rn2NleNJtyPTkNcNx70B1q3DHLeDB/7BhkxeR+GS9vQOGEORSEpjnfMwKe6EGfVGEwPG
eyArxr3hoDfwRsgpw0lv2FPRQe/ucP9qfyKeDcXFm7m4LJS4UKkYTvHfbDCdTYfiw+WpGA0AsUtB
I92koDDt7fdGuPtTJRCtM8LtwD680qbkAAC+ifimSk2G9PRTpmXgc9ajW8d4E9pt6XK4D4As8o3O
DNno7EZHF3qVk/pZj7/SohG4AEAlchkpMEae1O0EKgWbtA3PDDa9bAJiydmyQXqxeEMwZFWA8Oji
8uT95Yc5ALdqacKcON3keTrr929vb3sKrBDWXs5uZF3lBKw2BGsAm3KNYJSHyDV8vFw15dKLHReP
Eu4VFHSZycSsWnZrgduGG7CfNCQ0G73ehH76ZJYrES4WTTbad9+W10BgROCmWPZ8HfdLpP0WFtZA
XVWbCmjW2qb80+WwLf+lyjcqU8HVkymgQZyk5pu2B8/fXVx+fPf+/GVTbCo+5K/hOrnY6LTprSVo
JwZ3TXmHJ8twDWB59WRe6ziAz9a8fE2Y0mcdIz1V9F226VcYIOwpcnZ2LtfrhrQ1rCkukmVvx3Ln
L/+rJeDh34rKtdpevVRZLhMIWfHQvCYbvtJRQM7chn7VnUu7yhv1OrlpmtVBviHmvFhOfqYdT+Wf
ji6EqBh4gF/+JJPTKERn1qwPFawhA5hr8R8VvhwdpuoJa0NJdrcyfNkVd9JJxVO/FgEynkSRzcmm
IWQD2JJy1JJyo7dhEg8nsf9kYtaEF4sWEw+w1nugWOrbq7PVSvlNk+082C0OO+XvPIxOs9Ck25E+
6p8kaxVp8UsYZKF+MikdQ5afBxnUiXgS3MjEV8G/wrxlria4Kd7k89B6etdsUn8C72wJA5nRtMNV
QxmZy3lD5hZ4t0i0TfpUgjZJLhY7DDzIeujkXxVJy3IO9A2n/Fqodev+fcQ7H21Hywsir+bqAWKd
+TrR8fY/9bIhWAPY7jYHvUlbNJ2oJf5vyTUoxXL/jqp/h/zv2N2P3f3E3WOqeKz0jg3Y1XL+u14u
Fi0pHq6Kk/nrz1VBwF1VHP6/UAV4qVRhpXhY7Xydq7hdORmyM318vcH5G/4MVIuFI/o9SfbnTC5/
ks32rIS0OR/vBqmMwiLatgO0Ml9pv+9PQO3RppbPklss1uBuKdePTr0yUr/LJMg08PXrEwevbF7z
TKm+PR3sl5qgKQSiNqYP3P1vN3Urkj5+sF3fQKj3yqhma1DDGsyPdrq5VzK6fiqnJM1mRBDmatB+
APsv1c2lxiTc4L4C7dS/z8rHnK1KBMWlknFLmPHjE0VJf7FocPJ9Q27NWb/CQb2cWkOanwuZBc1G
rgFtifxMBaAQtIU+MdubcdKSdf/xhpOMbbGYZ+GNzJVlBeNujhZOZ1+CN+enL6946JQcp5GiCIrd
QXo1K7ce7LQSbaW8kbHcngTKFC3F/I0ojAmjJIyLhWFO1o6T3fsHFg5dJP72pwiO0fT1Fvgro9dL
mRVJKIeHLfmOHi9fhRDFpMFD++4RabfC228hohOCwuQ6PokwmTc10AK3jfw/fTLZJL1Y7DDyqFO8
eZGpucripoA1rC3daPfQZ3/y6tVg8GTSXVl8iNCSgcbl92c02ulKZ42FzLqR+YWfhctm7DaAu0I/
sLt4bD5z3YMPBgwz8D09EglGrO9Yj0FtOca98beN961juoZr3Nce1QefXzAq8VVf/W2TMpJP9DZB
ZhA+V+WYafi8gl52pAiOUNGrh2fz6k6c6mQVrgW9g11ki+TZRZGIt/qG33cczSaHs8lUnLy55Pcd
tCDWeXC8KAYDeRDZf0YfdRYF9nr/NJOrXNgbdXp+8lZ8mL88uTyjrZYVL9VZfjykPwS83UBGLwpN
fqxXK4LIJKHsQ90evbbypL8J1Y2KMdqaco1J5W3ipbZiQdPHw31mTt65XeZ4NGBkUaRvvVUUrjd5
e7NMwhiTchsY62UFKWvEMSNa6QwsVTC3ZoO67+usuk9v0mOd0FUQrlahX0T59pjltG/DUF09tFd5
mKzNMYEjSBZ55K/Ht6zGCmaUChpL6IX78cuzVycfzi8Jah3T+6NQ2daRdKAMY5GD0GUvlcYAd3D8
H/wHOily7Rl5o9wqekVV9di9bRyRiwiKPOGzdxRgnF8Uw0kEFCHqFsl7M4fTiMsNukZRSiZkpkS+
UQIjm8GFzIVPVs3FUokw8aMiUAEuxGfOSbgudIydK0Kwi9PIleoKTa8KDKEUy0zJa7HVReZwiXAl
YKBwFTIF2CaDhyCrAPFbdVuh6wdqJWEdI2518o9cyDRVMhOkmhjC+vCbLX2iQC+4rdy3G5WIIsVo
EwBBb5GQQ1tks0Uinl1uMJR4EUDgIpLJupBrJegDA1aZc34T4h5lFbnuT1YqbeWXrVaK9kYwUMa+
Snq34XWYoq2UPZ2t+3TXp48drvTq6vXFu6v98ZE3uqJ9UGOFiN44Z4VZdIjQxw2/ZqGvMwxylaAv
NUyesX5zGucidIOBfczaZE7BB65UziYN1E3oK7HBeBaxkWMgtsFRk6RkCbDZFHmgKazsa27iBalh
MhrS3+Mp/T0Z8PWoCRE1aLLka8l/8/VE8d8H9YZxYKU7oVgXlEogkHCzorgJpfg3RQmWcLSUU2TF
5rOLDfZJcnajIZTj1lpcOkSiMPBl5H/4EyvpZP4aK1FDAlJ3/cCD3pba1Fp4dsZxWeKB4gSlDAGv
h2MRq8utcO6I5S6Kq6c1no8hzKUTOKYMAoGRzfovcQmPvQY30qAUUKIU8NqlInXAdOqPQvIXOevw
BmtvZFQo8dxRRGLfA3JLDslDUXr24BPrtcpmKANE+W3BH/IgKDHBJP6lNNeIm+waYdij5x8MFEJe
XspIqzaZRiKHY2G16QpOb8KlQTh+F1qIoTT+XoS1goJHsBg9qM9LGPcFOx7kQYhm+g5JO1dQAcTh
gEkq1kiplp3XK4pz/gYJ8dwVYf4P+iQp412BoprBvryzVzyHBDCzGJFGWAbPSTkTIwp4Sv7ZlsP9
50gvoVUq/MKC4XlxmFNaizFfLLc5uBEXlo8BUw4NmdYmCwh0GzJXrGlBZcriKZVvWCmrEK6CTMff
+RCWFdJMSdHaHpIU7LBrDSE0xS0pDHTWzKTHjEGEweRwwQmHc3uOhCWD/+MSUOtU8j8cjCaWf/Rd
oeYKQo5vCKnPOdRhrZx7CEdAWAdkUF7hwfkUqcIiQveDZIFwAJMUiV+SwfKOXiXipEyBZZctuEYS
Drh6HTY2ZInCO4pXKkq8vPf5YgpV12VC2anyqXYZ1gnxaq1h91YCIGmr1NRijgdOTrN3L0NO6rGV
ei2zJZTt+TqKbPtEHn2vVtl2xIrbI9weBEosk4KrZJMLdBAFvGavWwbgjts4v7FJjN81Mfa49see
eGdLFN8Z1BBdREHFSIhwvU1EzTo5iUiZc3jI4WBgZRTPXrHbfZaI2Ffs7kqoVabjMp/RXvfca6aA
hk0hhDPdrivc4z+NfdSd+psiuTZW3+ccbZR9GEic0RBA0gjbxXY5FjL0DMYu8qhsU/tR4yJUpZld
oBztOz5fartt13z2W8RyWxODpeKWPYHMnPU9Hz28slI7XygJ0YOqwn0V1SJJVE62qLotuEZky85S
5hgSqOhLakxRbeBPLn9xANpe0j21aWupqgKkgqrQOI8tn1DgZ9uccHeFN2w4MxUaJuvlJStIK9N9
m1XqwsbdO1WVwOY6Z0C7F0DHU0/8EyMKf8EXU3NwOv/QxV5wsET+uQ2DfGNTJMd3hd5j9DMxcVW4
rs+GFdNY2hMnAeJpI6NVH325bRkCBT9zhEDS+p9OmgFZlcIGrplYYXSyzc0dBR/1HDLq2sAmwh/D
BJ0fxILbKHZtKqwf5sm8LMt1m00dB226xTC1oB47ST13y/2Po4WZSi2L9cxV+BdiSJXdGtNQB8eP
y+7NcB7bqLKrWzhTIEnUPZkRfZPLvIDD9Ne+VS3yWmBqtyuHsVanr8p+jdiGIHbG4aXOu0hatrcP
HebsYG6LZ7fMRIxHazcBQB4+YCBub+gQy+Yk2cKPxEkzVN4gD13mn3PDIcqWe/b23eXZTHDSxX9+
gXEowTjEiPgklCzH7DnKFXuVhU9axvLR+SOROFnZibgigRNympwcZzRwFYQymS1M5EU0dhLcVSMX
9G1wmcKmLiJtIVxKoxq0ng8RJvcQ6YoRHgzve6Byv7fHIWtUkwl2hkvCTLOQOzsQCmnJ0qPCbw3J
U2c9jlIa4HmDGhVKBjK6lVtjcTs8DddtZW/2opNYF0kz/RvXHpVMEPuEjbpzZGa6tI3Ll/bKDNDA
Mm+RtIuOGI4O793N3pUoO/ktlcW2VCtKRHwuQgmL7FBhtacljcw3Ycz0KROcFsNjSAOuokkn3bph
3pWiqp/hPLHil3hlVnRZbFVEvEwbuKpHERr6tpLwuJPRBA3PANpSV79rmjpsbBgZk7PEnCqpvlTy
lzFtjUEKLY3xRt4JuasWjBs+V4faH1q2YFO8l0FYmMYuZwXpeOMQtTud29F69GKUkOhUyivSAK5Y
O4vw6aM260g0zO7yXY9QJeu9z3l3ye9WhjwMY/AtlLOu289Bz3DPwFSuhnw3tlSnReSwuWuqS03E
PHRwSHpQHjFtz9489iIIPqGmDeZO+OceJXTokgOdVM3EPnd2pUHpI/MiRadj2z3rjpw6bJfhcAHL
Ae1yBI2bZyEIEaqADJPxkj5As0vcIZmdhmc2F9HcTh+6Cwu1Bdb5iPVd18bX5x/Y49GBTBtSFZMW
NN2kYbLStRtsNNmeSfYa53Pogpi/RCfbmHp8jg8D/ZqKURpa3GNRP2aG4WtSyPUatceN4dX5BjWI
9Ln/9f3SWH4InbmPH9KXdWU2cbW7FAdOYR/PrAWyxHOluV5jwTptBMOzUzrm43MnFemUylUX9xCC
DtXyshVDZ7JCp6ygbxSohOo8LXK1tSADISQbSIR7I9DoIQo0nCa3Fa7MeA4bGck+LvGbXUPRG6V7
1BKFqDjWMmd3kiquvaGOBQQcF7OSHSIEfze5hnf/SpceygzGKQB+WyQ2CZZdSPN4lEUopwU7spUn
zjyL3XfayqMtVzHDDQMJHaOPCMGlq/ANvpkqM8BXgg6oKXY5b9TUZuLV+cnlbPTjQXd6dDfsju/G
3dGPwx8DVGKbtp7T5xs+pZjjw4FYw8GNvZtM9/g0Wt3lKiFt8Ku4U5Shxo8ryIUat6gG686MTdHt
pD4tdTfmjyjM1dj+EsSzvzr50/40xL7JWvpoazbVejrpTAKZ1QD7I7fyrsii6mYVRvwbDaB2n9Gs
8rR6uo7r6w3Ct3rr/bupXqXRlyjx0h6+VovREm7TvJYgl8RQ0BD3Yn7OVOk69dHK1Xu3EJh/d+Ku
xJQ+eBmS5MKj9zejwXQwxuUPryksxwdjJadBMJ2ODw/2h5PBvjwcjEZysjyU44PJZHi4HE0GSvwA
SvMNqYW/D2PC2oR3tdLdqO4W8G833quVmzMBZXqHarryJRrVCcgOVgcH/sHh4f50CtLjo9FYjQfL
o4OjIGB6ZhPrWoWGo8q0JQ2t8rE419cqQaHJKshHJa+RD6yielNAtpLfatA3a7TgzzC1d6PepPPp
038DaQYfhA==
===END CRASH DUMP===

**Comment by LilCrispy2o9** [comment]
Dont do reloads, they are very bad.

**Comment by Tethered** [comment]
@LilCrispy2o9 is right
