### ISSUE TITLE
Spawn claimed!

### ISSUE THREAD

**Issue by Jorti1** [Tethered/FactionsPro#90]
I added a factionpro for fun. Two days later it was claimed by a faction . The faction name is disturbing ( It is inappropriate for m to post ) . It there a way to fix it or wait for a update?

**Comment by ChiefArtz** [comment]
u can edit in scr file

**Comment by Tethered** [comment]
This will be added when I reimplement plots

**Comment by Jorti1** [comment]
What part of the Scr file do we edit?
